# Generated by Django 5.1.3 on 2024-11-06 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecowaste', '0003_rename_items_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('quantity', models.CharField(max_length=50)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
