# Generated by Django 5.1.2 on 2024-12-03 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecowaste', '0006_article_pdf_alter_article_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
    ]
