# Generated by Django 5.1.2 on 2024-12-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecowaste', '0007_remove_article_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='pdf',
        ),
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(default='Default content for existing articles.'),
            preserve_default=False,
        ),
    ]
