# Generated by Django 5.1.2 on 2024-12-10 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecowaste', '0010_alter_wasteitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(default='Other', max_length=50),
        ),
    ]
